m0_j0_name: l_finger1
m0_j1_name: l_finger2
m0_j2_name: l_finger3
m1_j0_name: r_finger1
m1_j1_name: r_finger2
m1_j2_name: r_finger3
l_finger1_home_val: -1.2908448330057671
l_finger2_home_val: 1.22574652331987
l_finger3_home_val: 0.8218302071097322
r_finger1_home_val: -2.8745841226984488
r_finger2_home_val: 1.4529674275254307
r_finger3_home_val: 0.23527430334196023
l_finger1_val_negate: false
l_finger2_val_negate: false
l_finger3_val_negate: false
r_finger1_val_negate: true
r_finger2_val_negate: true
r_finger3_val_negate: true
l_finger_sensor0_offset: -25
l_finger_sensor1_offset: -21
l_finger_sensor2_offset: -26
l_finger_sensor3_offset: -28
r_finger_sensor0_offset: -28
r_finger_sensor1_offset: -20
r_finger_sensor2_offset: -23
r_finger_sensor3_offset: -21
